
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#pragma once

#include <unknwn.h>

// Undefine GetCurrentTime macro to prevent
// conflict with Storyboard::GetCurrentTime
#undef GetCurrentTime

#if __has_include(<winrt/Microsoft.UI.Xaml.h>)
#include <winrt/Microsoft.UI.Xaml.h>
#endif
#if __has_include(<winrt/Microsoft.UI.Xaml.Controls.h>)
#include <winrt/Microsoft.UI.Xaml.Controls.h>
#endif
#if __has_include(<winrt/Microsoft.UI.Xaml.Controls.Primitives.h>)
#include <winrt/Microsoft.UI.Xaml.Controls.Primitives.h>
#endif
#if __has_include(<winrt/Microsoft.UI.Xaml.Markup.h>)
#include <winrt/Microsoft.UI.Xaml.Markup.h>
#endif


namespace winrt::demo::implementation
{
    using IInspectable = ::winrt::Windows::Foundation::IInspectable;

    template <typename D, typename ... I>
    struct MainWindowT : public ::winrt::demo::implementation::MainWindow_base<D,
        ::winrt::Microsoft::UI::Xaml::Markup::IComponentConnector,
        I...>
    {
        using base_type = typename MainWindowT::base_type;
        using base_type::base_type;
        using class_type = typename MainWindowT::class_type;

        void InitializeComponent();
        virtual void Connect(int32_t connectionId, IInspectable const& target);
        virtual ::winrt::Microsoft::UI::Xaml::Markup::IComponentConnector GetBindingConnector(int32_t connectionId, IInspectable const& target);
        void UnloadObject(::winrt::Microsoft::UI::Xaml::DependencyObject const& dependencyObject);
        void DisconnectUnloadedObject(int32_t connectionId);

        ::winrt::Microsoft::UI::Xaml::Controls::ListView ProcessTableListView()
        {
            return _ProcessTableListView;
        }
        void ProcessTableListView(::winrt::Microsoft::UI::Xaml::Controls::ListView value)
        {
            _ProcessTableListView = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Canvas GanttCanvas()
        {
            return _GanttCanvas;
        }
        void GanttCanvas(::winrt::Microsoft::UI::Xaml::Controls::Canvas value)
        {
            _GanttCanvas = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock CurrentTimeText()
        {
            return _CurrentTimeText;
        }
        void CurrentTimeText(::winrt::Microsoft::UI::Xaml::Controls::TextBlock value)
        {
            _CurrentTimeText = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock AvgWaitText()
        {
            return _AvgWaitText;
        }
        void AvgWaitText(::winrt::Microsoft::UI::Xaml::Controls::TextBlock value)
        {
            _AvgWaitText = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock AvgTurnaroundText()
        {
            return _AvgTurnaroundText;
        }
        void AvgTurnaroundText(::winrt::Microsoft::UI::Xaml::Controls::TextBlock value)
        {
            _AvgTurnaroundText = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::ComboBox SchedulerCombo()
        {
            return _SchedulerCombo;
        }
        void SchedulerCombo(::winrt::Microsoft::UI::Xaml::Controls::ComboBox value)
        {
            _SchedulerCombo = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::TextBox BurstTimeInput()
        {
            return _BurstTimeInput;
        }
        void BurstTimeInput(::winrt::Microsoft::UI::Xaml::Controls::TextBox value)
        {
            _BurstTimeInput = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::TextBox ArrivalTimeInput()
        {
            return _ArrivalTimeInput;
        }
        void ArrivalTimeInput(::winrt::Microsoft::UI::Xaml::Controls::TextBox value)
        {
            _ArrivalTimeInput = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::TextBox PriorityInput()
        {
            return _PriorityInput;
        }
        void PriorityInput(::winrt::Microsoft::UI::Xaml::Controls::TextBox value)
        {
            _PriorityInput = value;
        }
        
    protected:
        bool _contentLoaded{false};

    private:
        struct MainWindow_obj1_Bindings;

        ::winrt::Microsoft::UI::Xaml::Controls::ListView _ProcessTableListView{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Canvas _GanttCanvas{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock _CurrentTimeText{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock _AvgWaitText{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock _AvgTurnaroundText{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::ComboBox _SchedulerCombo{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::TextBox _BurstTimeInput{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::TextBox _ArrivalTimeInput{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::TextBox _PriorityInput{nullptr};
    };
}

