// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.250303.1

void* winrt_make_demo_MainWindow()
{
    return winrt::detach_abi(winrt::make<winrt::demo::factory_implementation::MainWindow>());
}
WINRT_EXPORT namespace winrt::demo
{
    MainWindow::MainWindow() :
        MainWindow(make<demo::implementation::MainWindow>())
    {
    }
}
