// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.250303.1

void* winrt_make_demo_XamlMetaDataProvider()
{
    return winrt::detach_abi(winrt::make<winrt::demo::factory_implementation::XamlMetaDataProvider>());
}
WINRT_EXPORT namespace winrt::demo
{
    XamlMetaDataProvider::XamlMetaDataProvider() :
        XamlMetaDataProvider(make<demo::implementation::XamlMetaDataProvider>())
    {
    }
}
