// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.250303.1

#pragma once
#ifndef WINRT_demo_0_H
#define WINRT_demo_0_H
WINRT_EXPORT namespace winrt::Microsoft::UI::Xaml::Markup
{
    struct IXamlMetadataProvider;
}
WINRT_EXPORT namespace winrt::demo
{
    struct IMainWindow;
    struct MainWindow;
    struct XamlMetaDataProvider;
}
namespace winrt::impl
{
    template <> struct category<winrt::demo::IMainWindow>{ using type = interface_category; };
    template <> struct category<winrt::demo::MainWindow>{ using type = class_category; };
    template <> struct category<winrt::demo::XamlMetaDataProvider>{ using type = class_category; };
    template <> inline constexpr auto& name_v<winrt::demo::MainWindow> = L"demo.MainWindow";
    template <> inline constexpr auto& name_v<winrt::demo::XamlMetaDataProvider> = L"demo.XamlMetaDataProvider";
    template <> inline constexpr auto& name_v<winrt::demo::IMainWindow> = L"demo.IMainWindow";
    template <> inline constexpr guid guid_v<winrt::demo::IMainWindow>{ 0xB69F3F0F,0xF45E,0x5A22,{ 0x88,0xC3,0xBF,0xD7,0x16,0xA5,0x8A,0xF0 } }; // B69F3F0F-F45E-5A22-88C3-BFD716A58AF0
    template <> struct default_interface<winrt::demo::MainWindow>{ using type = winrt::demo::IMainWindow; };
    template <> struct default_interface<winrt::demo::XamlMetaDataProvider>{ using type = winrt::Microsoft::UI::Xaml::Markup::IXamlMetadataProvider; };
    template <> struct abi<winrt::demo::IMainWindow>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
            virtual int32_t __stdcall get_MyProperty(int32_t*) noexcept = 0;
            virtual int32_t __stdcall put_MyProperty(int32_t) noexcept = 0;
        };
    };
    template <typename D>
    struct consume_demo_IMainWindow
    {
        [[nodiscard]] auto MyProperty() const;
        auto MyProperty(int32_t value) const;
    };
    template <> struct consume<winrt::demo::IMainWindow>
    {
        template <typename D> using type = consume_demo_IMainWindow<D>;
    };
}
#endif
