// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.250303.1

#pragma once
#ifndef WINRT_demo_H
#define WINRT_demo_H
#include "winrt/base.h"
static_assert(winrt::check_version(CPPWINRT_VERSION, "2.0.250303.1"), "Mismatched C++/WinRT headers.");
#define CPPWINRT_VERSION "2.0.250303.1"
#include "winrt/impl/Microsoft.UI.Xaml.2.h"
#include "winrt/impl/Microsoft.UI.Xaml.Markup.2.h"
#include "winrt/impl/demo.2.h"
namespace winrt::impl
{
    template <typename D> auto consume_demo_IMainWindow<D>::MyProperty() const
    {
        int32_t value{};
        if constexpr (!std::is_same_v<D, winrt::demo::IMainWindow>)
        {
            winrt::hresult _winrt_cast_result_code;
            auto const _winrt_casted_result = impl::try_as_with_reason<winrt::demo::IMainWindow, D const*>(static_cast<D const*>(this), _winrt_cast_result_code);
            check_hresult(_winrt_cast_result_code);
            auto const _winrt_abi_type = *(abi_t<winrt::demo::IMainWindow>**)&_winrt_casted_result;
            check_hresult(_winrt_abi_type->get_MyProperty(&value));
        }
        else
        {
            auto const _winrt_abi_type = *(abi_t<winrt::demo::IMainWindow>**)this;
            check_hresult(_winrt_abi_type->get_MyProperty(&value));
        }
        return value;
    }
    template <typename D> auto consume_demo_IMainWindow<D>::MyProperty(int32_t value) const
    {
        if constexpr (!std::is_same_v<D, winrt::demo::IMainWindow>)
        {
            winrt::hresult _winrt_cast_result_code;
            auto const _winrt_casted_result = impl::try_as_with_reason<winrt::demo::IMainWindow, D const*>(static_cast<D const*>(this), _winrt_cast_result_code);
            check_hresult(_winrt_cast_result_code);
            auto const _winrt_abi_type = *(abi_t<winrt::demo::IMainWindow>**)&_winrt_casted_result;
            check_hresult(_winrt_abi_type->put_MyProperty(value));
        }
        else
        {
            auto const _winrt_abi_type = *(abi_t<winrt::demo::IMainWindow>**)this;
            check_hresult(_winrt_abi_type->put_MyProperty(value));
        }
    }
    template <typename D>
    struct produce<D, winrt::demo::IMainWindow> : produce_base<D, winrt::demo::IMainWindow>
    {
        int32_t __stdcall get_MyProperty(int32_t* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *value = detach_from<int32_t>(this->shim().MyProperty());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall put_MyProperty(int32_t value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().MyProperty(value);
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
}
WINRT_EXPORT namespace winrt::demo
{
}
namespace std
{
#ifndef WINRT_LEAN_AND_MEAN
    template<> struct hash<winrt::demo::IMainWindow> : winrt::impl::hash_base {};
    template<> struct hash<winrt::demo::MainWindow> : winrt::impl::hash_base {};
    template<> struct hash<winrt::demo::XamlMetaDataProvider> : winrt::impl::hash_base {};
#endif
#ifdef __cpp_lib_format
#endif
}
#endif
